# Generated by Django 4.0.6 on 2022-08-13 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoOP', '0002_avbooked_rename_username_user_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avbooked',
            old_name='dateBooked',
            new_name='date_booked',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avbooked',
        ),
        migrations.AddField(
            model_name='avbooked',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoOP.user'),
        ),
    ]
