# Generated by Django 4.0.6 on 2022-08-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoOP', '0003_rename_datebooked_avbooked_date_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avbooked',
            name='date_booked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
